version: '3.8'

services:
  agent-mongo-prod:
    image: mongo:7
    container_name: agent-mongo-prod
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - agent-mongo-prod-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    command: ["mongod", "--bind_ip_all"]

volumes:
  agent-mongo-prod-data:
    external: false